name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-22.04
        name: Amazon Linux 2023

        strategy:
            matrix:
                image:
                -   tayloraswift/5.10.0-amazonlinux2023:latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run pipeline
                run: |
                    docker run -t --rm \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift-hash \
                        -w /swift-hash \
                        ${{ matrix.image }} \
                        .github/pipeline

    macos:
        runs-on: macos-14
        name: macOS
        env:
            DEVELOPER_DIR: "/Applications/Xcode_15.3.app/Contents/Developer"

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build iOS
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "CRC" -destination \
                        "generic/platform=ios"
                    xcrun xcodebuild build -scheme "MD5" -destination \
                        "generic/platform=ios"
                    xcrun xcodebuild build -scheme "SHA1" -destination \
                        "generic/platform=ios"
                    xcrun xcodebuild build -scheme "SHA2" -destination \
                        "generic/platform=ios"
                    xcrun xcodebuild build -scheme "Base64" -destination \
                        "generic/platform=ios"

            -   name: Build tvOS
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "CRC" -destination \
                        "generic/platform=tvos"
                    xcrun xcodebuild build -scheme "MD5" -destination \
                        "generic/platform=tvos"
                    xcrun xcodebuild build -scheme "SHA1" -destination \
                        "generic/platform=tvos"
                    xcrun xcodebuild build -scheme "SHA2" -destination \
                        "generic/platform=tvos"
                    xcrun xcodebuild build -scheme "Base64" -destination \
                        "generic/platform=tvos"

            -   name: Build watchOS
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "CRC" -destination \
                        "generic/platform=watchos"
                    xcrun xcodebuild build -scheme "MD5" -destination \
                        "generic/platform=watchos"
                    xcrun xcodebuild build -scheme "SHA1" -destination \
                        "generic/platform=watchos"
                    xcrun xcodebuild build -scheme "SHA2" -destination \
                        "generic/platform=watchos"
                    xcrun xcodebuild build -scheme "Base64" -destination \
                        "generic/platform=watchos"

            -   name: Run pipeline
                run: .github/pipeline
